# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='winner_team',
            new_name='team_1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='looser_team',
            new_name='team_2',
        ),
        migrations.RenameField(
            model_name='matchset',
            old_name='looser_points',
            new_name='team_1_points',
        ),
        migrations.RenameField(
            model_name='matchset',
            old_name='winner_points',
            new_name='team_2_points',
        ),
        migrations.RemoveField(
            model_name='match',
            name='looser_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner_score',
        ),
        migrations.AddField(
            model_name='match',
            name='state',
            field=models.CharField(blank=True, choices=[('win', 'win'), ('lost', 'lost'), ('tie', 'tie')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_1_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
