# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='lost_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='lost_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='win_lost_points_ratio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='player',
            name='win_percent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='player',
            name='won_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='won_point',
            field=models.IntegerField(default=0),
        ),
    ]
