# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_tie_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='win_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
